--CONSULTA1
SELECT * FROM CODIGO

--CONSULTA2
SELECT count(DISTINCT(CTI_ID)) FROM ASESOR

--CONSULTA3
SELECT avg(DUR_CALL)
FROM ASESOR

--CONSULTA4
SELECT CTI_ID,avg(DUR_CALL)
FROM ASESOR
GROUP BY CTI_ID

--CONSULTA5
SELECT COD_OPC_MENU,avg(DURA_LLAM)
FROM IVR
GROUP BY COD_OPC_MENU

--CONSULTA6
SELECT count(DISTINCT(ASESOR.CALL_CONNID)) AS LLAMADAS_PASO_ASESOR FROM ASESOR 
LEFT JOIN IVR ON ASESOR.CALL_CONNID=IVR.CONNID

--CONSULTA7
SELECT count(DISTINCT(IVR.CONNID)) AS LLAMADAS_NO_PASO_ASESOR FROM IVR 
LEFT JOIN ASESOR ON IVR.CONNID=ASESOR.CALL_CONNID
WHERE ASESOR.CALL_CONNID IS NULL